# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on:
  push:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - name: checkout source
    - uses: actions/checkout@v3
    - name: login to docker hub
    - uses: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PWD }}
    - name: build docker image
    - uses: docker build -t ci-cd/node .
    - name: publish image to docker hub
    - uses: docker push ci-cd/node:latest
  deploy:
    needs: build
    runs_on: [own3]

    steps:
    - name: pull docker image
    - uses: docker pull ci-cd/node:latest
    - name: delete old container
    - uses: docker rm -f node-app-container
    - name: run docker container
    - uses: docker run -d -p 5000:5000 --name node-app-container  ci-cd/node:latest